apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  restartPolicy : Never
  initContainers:
    - name: db-migration
      image: busybox
      command: [sh -c 'echo "Run DB Migration" sleep 10 && exit 0']
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80