apiVersion: v1
kind: Pod
metadata:
  name: springboot-app
spec:
  restartPolicy: Never
  initContainers:
    name: db-migration
    image: busybox
    command: [sh -c 'echo "Run DB migration" && sleep 5 && exit 0']
  containers:
    - name: springboot-app-container
      image: myrepo/springboot-app:1.0
      ports:
        - containerPort: 8080
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExection:
            - labelSelector:
               matchExpressions:
                - key: app
                  operator: In
                  values:
                    - my-backend
            toplogykey: "kuberneteds.io/hostname"